import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore, DATA_KEY} from '../crm/data/store.mjs';
import {createDemoState} from '../crm/data/fixtures.mjs';
export function memory(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
const setup=()=>{const storage=memory();let id=0;return {storage,store:createStore({storage,sessionStorage:memory(),now:()=>new Date('2026-10-08T10:00:00Z'),makeId:()=>`test-${++id}`})};};
test('fresh state, edits and reload preserve relations',()=>{const {storage,store}=setup();assert.equal(store.load().ok,true);const result=store.dispatch('client.save',{name:'Novo exemplo',type:'business',city:'Setúbal',contact:''});assert.equal(result.ok,true);const second=createStore({storage,sessionStorage:memory()});assert.equal(second.load().ok,true);assert.ok(second.getState().clients.some(c=>c.name==='Novo exemplo'));});
test('invalid JSON and future versions are never silently replaced',()=>{for(const bad of ['{bad',JSON.stringify({version:900})]){const {storage,store}=setup();storage.setItem(DATA_KEY,bad);assert.equal(store.load().ok,false);assert.equal(storage.getItem(DATA_KEY),bad);}});
test('write failure keeps original state',()=>{const {storage,store}=setup();store.load();const before=JSON.stringify(store.getState());storage.setItem=()=>{throw new Error('quota');};assert.equal(store.dispatch('client.save',{name:'Example',type:'business'}).ok,false);assert.equal(JSON.stringify(store.getState()),before);});
test('reset and logout preserve unrelated data',()=>{const {storage,store}=setup();store.load();storage.setItem('other','keep');store.enterDemo();assert.equal(store.isDemoSession(),true);store.exitDemo();assert.equal(store.isDemoSession(),false);assert.ok(storage.getItem(DATA_KEY));store.resetDemo();assert.equal(storage.getItem('other'),'keep');});
test('stale revision rejects a second-tab write',()=>{const {storage,store}=setup();store.load();const other=createStore({storage,sessionStorage:memory()});other.load();store.dispatch('client.save',{name:'First',type:'business'});assert.equal(other.dispatch('client.save',{name:'Stale',type:'business'}).ok,false);});
test('corrupt boolean types and closed-job reservations trigger recovery',()=>{for(const corrupt of [s=>s.orders[0].artApproved='false',s=>s.jobs[1].consumptionConfirmed='false',s=>s.jobs[1].status='cancelled']){const {storage,store}=setup();const s=createDemoState();corrupt(s);const raw=JSON.stringify(s);storage.setItem(DATA_KEY,raw);assert.equal(store.load().ok,false);assert.equal(storage.getItem(DATA_KEY),raw);}});
