import test from 'node:test';import assert from 'node:assert/strict';
import {createDemoState} from '../crm/data/fixtures.mjs';import {applyCommand} from '../crm/domain/commands.mjs';import {getLotBalance} from '../crm/domain/inventory.mjs';
let seq=0;const cmd=(s,type,payload,id=`cmd-${++seq}`)=>applyCommand(s,{id,type,payload,actorId:'user-demo',at:'2026-10-08T10:00:00Z'});
function base(){const s=createDemoState(new Date('2026-10-08T10:00:00Z'));s.lots=[{id:'lot-test',material:'PLA',brand:'Demo',color:'Preto',receivedGrams:1000,purchaseCostMilliEuro:20000,lowStockGrams:100}];s.reservations=[];s.movements=[];s.orders[0].status='production';s.jobs[0].status='pending';return s;}
test('reserve 200 then consume 120, release remainder and preserve cost',()=>{let s=base();const j=s.jobs[0].id;s=cmd(s,'job.start',{jobId:j,reservations:[{lotId:'lot-test',grams:200}]}).state;assert.deepEqual(getLotBalance(s,'lot-test'),{physical:1000,reserved:200,available:800});const input={jobId:j,outcome:'completed',consumptions:[{lotId:'lot-test',grams:120}]};const r=cmd(s,'job.confirmConsumption',input,'finish');assert.equal(r.ok,true);assert.deepEqual(getLotBalance(r.state,'lot-test'),{physical:880,reserved:0,available:880});assert.equal(r.state.movements.at(-1).costMilliEuro,2400);assert.deepEqual(cmd(r.state,'job.confirmConsumption',input,'finish').state,r.state);assert.equal(cmd(r.state,'job.confirmConsumption',input).ok,false);});
test('invalid grams and shortage fail atomically',()=>{for(const grams of [-1,NaN,1.5,1001]){const s=base(),before=JSON.stringify(s);assert.equal(cmd(s,'job.start',{jobId:s.jobs[0].id,reservations:[{lotId:'lot-test',grams}]}).ok,false);assert.equal(JSON.stringify(s),before);}});
test('other jobs reservations limit real consumption',()=>{let s=base();s=cmd(s,'job.start',{jobId:s.jobs[0].id,reservations:[{lotId:'lot-test',grams:100}]}).state;s.reservations.push({jobId:s.jobs[1].id,lotId:'lot-test',grams:800});assert.equal(cmd(s,'job.confirmConsumption',{jobId:s.jobs[0].id,outcome:'completed',consumptions:[{lotId:'lot-test',grams:250}]}).ok,false);});
test('cancel frees reserved material without consuming',()=>{let s=base();const jobId=s.jobs[0].id;s=cmd(s,'job.start',{jobId,reservations:[{lotId:'lot-test',grams:200}]}).state;s=cmd(s,'job.cancel',{jobId}).state;assert.deepEqual(getLotBalance(s,'lot-test'),{physical:1000,reserved:0,available:1000});});
test('failure consumes material and reprint is a new job',()=>{let s=base();const jobId=s.jobs[0].id;s=cmd(s,'job.start',{jobId,reservations:[]}).state;s=cmd(s,'job.confirmConsumption',{jobId,outcome:'failed',consumptions:[{lotId:'lot-test',grams:30}]}).state;s=cmd(s,'job.reprint',{jobId}).state;assert.equal(getLotBalance(s,'lot-test').physical,970);assert.equal(s.jobs.at(-1).parentJobId,jobId);assert.notEqual(s.jobs.at(-1).id,jobId);});
test('new purchases do not reprice historical consumption',()=>{let s=base();const jobId=s.jobs[0].id;s=cmd(s,'job.start',{jobId,reservations:[]}).state;s=cmd(s,'job.confirmConsumption',{jobId,outcome:'completed',consumptions:[{lotId:'lot-test',grams:120}]}).state;const before=structuredClone(s.movements);s=cmd(s,'lot.add',{material:'PLA',color:'Preto',receivedGrams:1000,purchaseCostMilliEuro:50000,lowStockGrams:100}).state;assert.deepEqual(s.movements,before);assert.equal(s.lots.length,2);});
test('zero consumption releases reservation, duplicate lots fail atomically',()=>{let s=base();const jobId=s.jobs[0].id;s=cmd(s,'job.start',{jobId,reservations:[{lotId:'lot-test',grams:200}]}).state;const before=JSON.stringify(s);assert.equal(cmd(s,'job.confirmConsumption',{jobId,outcome:'completed',consumptions:[{lotId:'lot-test',grams:10},{lotId:'lot-test',grams:20}]}).ok,false);assert.equal(JSON.stringify(s),before);s=cmd(s,'job.confirmConsumption',{jobId,outcome:'completed',consumptions:[{lotId:'lot-test',grams:0}]}).state;assert.deepEqual(getLotBalance(s,'lot-test'),{physical:1000,reserved:0,available:1000});});
