import * as quotes from './views/quotes.mjs';
import {createStore} from './data/store.mjs';import {el,button,link,notice} from './ui/dom.mjs';import {openDialog} from './ui/dialog.mjs';
import {icon} from './ui/icons.mjs';import {reveal} from './ui/motion.mjs';
import * as today from './views/today.mjs';import * as clients from './views/clients.mjs';import * as pipeline from './views/pipeline.mjs';import * as order from './views/order.mjs';import * as tasks from './views/tasks.mjs';import * as catalog from './views/catalog.mjs';import * as materials from './views/materials.mjs';import * as settings from './views/settings.mjs';
const routes={hoje:['Hoje',today,'◈'],clientes:['Clientes',clients,'◎'],pipeline:['Pipeline',pipeline,'▥'],orcamentos:['Orçamentos',quotes],tarefas:['Tarefas',tasks,'☑'],catalogo:['Catálogo',catalog,'▧'],filamentos:['Filamentos',materials,'◉'],definicoes:['Definições',settings,'⚙']};
const safeStorage=key=>({getItem:name=>window[key].getItem(name),setItem:(name,value)=>window[key].setItem(name,value),removeItem:name=>window[key].removeItem(name)});
const store=createStore({storage:safeStorage('localStorage'),sessionStorage:safeStorage('sessionStorage')});let loaded=store.load();if(loaded.ok)loaded=store.addTaskExamples();const app=document.querySelector('#app');let toastTimer;
function announce(message){const node=document.querySelector('#announcement');node.replaceChildren(icon('check'),el('span',{},message));reveal(node,'toast');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.replaceChildren(),5000);}
function dispatch(type,payload){const result=store.dispatch(type,payload);if(result.ok){render();if(!document.querySelector('dialog[open]'))document.querySelector('#workspace h1')?.focus();announce('Alteração guardada nesta demonstração.');}else announce(result.message);return result;}
function resetDemo(){const r=store.resetDemo();if(r.ok){loaded=r;render();announce('Exemplos repostos.');}return r;}
function render(animate=false){
  if(!loaded.ok){app.replaceChildren(el('main',{class:'login-card',id:'workspace'},el('h1',{},'Recuperar demonstração'),notice(loaded.message),button('Tentar novamente',()=>{loaded=store.load();render();}),button('Repor exemplos',()=>openDialog({title:'Substituir dados locais?',body:notice('Os dados atuais do CRM serão substituídos. Nenhuma outra aplicação será afetada.'),saveLabel:'Repor exemplos',onSave:resetDemo}),'secondary')));return;}
  if(!store.isDemoSession()){app.replaceChildren(el('div',{class:'login-screen'},el('main',{class:'login-card',id:'workspace'},el('img',{src:'../assets/logo.jpeg',alt:'Arrábida 3D Print',class:'login-logo'}),el('p',{class:'eyebrow'},'O lado de dentro do estúdio'),el('h1',{},'Tudo começa aqui.'),el('p',{class:'muted'},'Clientes, encomendas e produção. Um lugar para acompanhar cada detalhe.'),el('div',{class:'account'},el('span',{class:'avatar'},'AD'),el('div',{},el('strong',{},'Administrador demo'),el('p',{class:'small muted'},'Conta única de demonstração'))),button('Entrar na demonstração',()=>{const r=store.enterDemo();if(r.ok)render();else announce(r.message);}),notice('Usa apenas dados fictícios. Sem palavra-passe real; esta entrada não protege dados.'),link('Voltar ao website','../index.html','text-link'))));return;}
  const [route='hoje',id]=location.hash.slice(1).split('/');const active=route||'hoje';const config=active==='encomenda'?['Projeto',order]:active==='cliente'?['Ficha de cliente',clients]:routes[active];
  const ctx={state:store.getState(),id,now:()=>new Date(),navigate:r=>location.hash=r,dispatch,openDialog,resetDemo};
  const current=app.querySelector('.shell');
  if(current){
    current.querySelector('.breadcrumb').textContent='Estúdio / '+(config?.[0]||'Página');
    current.querySelector('h1').textContent=config?.[0]||'Página não encontrada';
    current.querySelectorAll('.nav-link').forEach(a=>{const selected=a.hash==='#'+(active==='encomenda'?'pipeline':active==='cliente'?'clientes':active);a.classList.toggle('selected',selected);if(selected)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
    const view=current.querySelector('.view');view.replaceChildren(config?config[1].render(ctx):el('div',{},notice('Esta página não existe.'),link('Voltar a Hoje','#hoje')));
    if(animate){view.scrollTop=0;reveal(view);}
    return;
  }
  const nav=el('nav',{class:'sidebar-nav',id:'crm-navigation','aria-label':'Gestão'},Object.entries(routes).map(([key,[label]])=>{const a=link(el('span',{},el('span',{class:'nav-icon'},icon(key)),el('span',{class:'nav-text'},label)),`#${key}`,`nav-link ${(active===key||active==='encomenda'&&key==='pipeline'||active==='cliente'&&key==='clientes')?'selected':''}`);a.setAttribute('aria-label',label);a.title=label;if(a.classList.contains('selected'))a.setAttribute('aria-current','page');return a;}));
  const sidebar=el('aside',{class:'sidebar'},link(el('div',{class:'brand'},el('img',{src:'../assets/logo.jpeg',alt:'',width:68,height:56}),el('span',{},el('strong',{},'ARRÁBIDA'),el('small',{},'Gestão do estúdio'))),'#hoje'),el('p',{class:'nav-label'},'Espaço de trabalho'),nav,el('div',{class:'sidebar-bottom'},link('Ver website ↗','../index.html'),el('div',{class:'account'},el('span',{class:'avatar'},'AD'),el('div',{},el('strong',{},'Administrador'),el('small',{},'Conta demo'))),button('Sair',()=>{const r=store.exitDemo();if(r.ok)render();else announce(r.message);},'logout')));
  const toggle=button('Menu',()=>{const open=sidebar.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));},'secondary mobile-menu');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','crm-navigation');
  sidebar.id='crm-sidebar';
  sidebar.querySelector('a').setAttribute('aria-label','Arrábida — Hoje');
  const fold=button(icon('collapse'),()=>{const compact=sidebar.closest('.shell').classList.toggle('compact');fold.setAttribute('aria-expanded',String(!compact));fold.setAttribute('aria-label',compact?'Expandir navegação':'Recolher navegação');fold.title=compact?'Expandir navegação':'Recolher navegação';},'ghost sidebar-fold');fold.setAttribute('aria-label','Recolher navegação');fold.setAttribute('aria-expanded','true');fold.setAttribute('aria-controls','crm-sidebar');fold.title='Recolher navegação';sidebar.insertBefore(fold,sidebar.querySelector('.nav-label'));
  const workspace=el('main',{id:'workspace',class:'workspace'},el('header',{class:'topbar'},el('div',{},el('p',{class:'breadcrumb'},'Estúdio / '+(config?.[0]||'Página')),el('h1',{tabindex:-1},config?.[0]||'Página não encontrada')),el('div',{class:'topbar-right'},el('span',{class:'today-date'},new Date().toLocaleDateString('pt-PT',{day:'numeric',month:'long'})),toggle)),el('div',{class:'demo-banner'},el('span',{class:'demo-dot','aria-hidden':'true'}),'Demonstração — usa apenas dados fictícios',el('span',{class:'demo-local'},'Guardado neste browser')),el('div',{class:'view'},config?config[1].render(ctx):el('div',{},notice('Esta página não existe.'),link('Voltar a Hoje','#hoje'))));
  app.replaceChildren(el('div',{class:'shell compact'},sidebar,workspace));fold.setAttribute('aria-expanded','false');fold.setAttribute('aria-label','Expandir navegação');fold.title='Expandir navegação';
}
window.addEventListener('hashchange',()=>{document.querySelectorAll('dialog').forEach(d=>d.close());document.querySelector('.sidebar')?.classList.remove('open');document.querySelector('.mobile-menu')?.setAttribute('aria-expanded','false');render(true);document.querySelector('#workspace h1')?.focus();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const side=document.querySelector('.sidebar.open');if(side){side.classList.remove('open');const b=document.querySelector('.mobile-menu');b?.setAttribute('aria-expanded','false');b?.focus();}}});
window.addEventListener('storage',e=>{if(e.key==='arrabida.crm.demo.v1')announce('Os dados mudaram noutra aba. Recarrega antes de editar.');});
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();const target=document.querySelector('#workspace h1')||document.querySelector('#workspace');if(target){target.tabIndex=-1;target.focus();target.scrollIntoView({block:'start'});}});
render();
