import {el,button,panel,table,field,data,empty,euro,notice} from '../ui/dom.mjs';import {getLotBalance} from '../domain/inventory.mjs';
export function materialDialog(ctx,job,confirm=false){
  const fields=el('div',{class:'stack'},notice(confirm?'Confirma todo o consumo real, incluindo suportes e desperdício. Zero gramas liberta a reserva sem consumo.':'Reserva o consumo previsto. O stock físico só é descontado na confirmação final.'));
  for(const lot of ctx.state.lots){const own=ctx.state.reservations.filter(r=>r.jobId===job.id&&r.lotId===lot.id).reduce((n,r)=>n+r.grams,0);fields.append(field(`${lot.material} · ${lot.color} (${getLotBalance(ctx.state,lot.id).available+own} g disponíveis para este trabalho)`,lot.id,confirm?own:0,{type:'number',min:0,step:1,required:true}));}
  if(confirm)fields.append(field('Resultado da produção','outcome','completed',{choices:[['completed','Concluído'],['failed','Falhou — material consumido']]}));
  ctx.openDialog({title:confirm?'Confirmar consumo real':'Iniciar trabalho e reservar',body:fields,saveLabel:confirm?'Confirmar consumo':'Iniciar trabalho',onSave:form=>{const values=data(form),rows=ctx.state.lots.map(l=>({lotId:l.id,grams:Number(values[l.id])}));return ctx.dispatch(confirm?'job.confirmConsumption':'job.start',confirm?{jobId:job.id,outcome:values.outcome,consumptions:rows}:{jobId:job.id,reservations:rows.filter(r=>r.grams!==0)});}});
}
export function render(ctx){const s=ctx.state;const add=()=>ctx.openDialog({title:'Registar entrada de filamento',body:el('div',{class:'form-grid'},field('Material','material','PLA',{required:true,maxlength:60}),field('Marca','brand','',{maxlength:80}),field('Cor','color','',{required:true,maxlength:60}),field('Peso recebido (g)','receivedGrams',1000,{type:'number',min:1,step:1,required:true}),field('Custo de compra (€)','cost',20,{type:'number',min:0,step:.001,required:true}),field('Avisar abaixo de (g)','lowStockGrams',150,{type:'number',min:0,step:1,required:true})),onSave:form=>{const p=data(form);return ctx.dispatch('lot.add',{...p,receivedGrams:Number(p.receivedGrams),purchaseCostMilliEuro:Math.round(Number(p.cost)*1000),lowStockGrams:Number(p.lowStockGrams)});}});
  const rows=s.lots.map(l=>{const b=getLotBalance(s,l.id);return [el('div',{},el('strong',{},`${l.material} · ${l.color}`),el('p',{class:'small muted'},l.brand||'Sem marca')),`${b.physical} g`,`${b.reserved} g`,el('strong',{class:b.available<=l.lowStockGrams?'stock-low':''},`${b.available} g`),new Intl.NumberFormat('pt-PT',{minimumFractionDigits:3,maximumFractionDigits:4}).format(l.purchaseCostMilliEuro/l.receivedGrams/1000)+' €/g',b.available<=l.lowStockGrams?el('span',{class:'badge quote'},'Repor stock'):el('span',{class:'badge completed'},'Disponível')];});
  const movements=s.movements.slice().reverse().map(m=>{const l=s.lots.find(l=>l.id===m.lotId);return [`${l.material} · ${l.color}`,`${m.deltaGrams} g`,euro(m.costMilliEuro),new Date(m.at).toLocaleString('pt-PT'),s.jobs.find(j=>j.id===m.jobId)?.title||'Trabalho'];});
  return el('div',{class:'stack'},el('div',{class:'toolbar'},notice('Stock físico, reserva e disponível são valores distintos.'),button('+ Entrada de filamento',add)),panel('Materiais do estúdio',table(['Filamento / lote','Físico','Reservado','Disponível','Custo','Estado'],rows)),panel('Consumos confirmados',movements.length?table(['Material','Consumo','Custo de filamento','Data','Trabalho'],movements):empty('Ainda não há consumos.')));
}
