import {hasCatalogPrice} from '../domain/catalog-pricing.mjs';
import {quotationDialog,quotationSummary} from '../ui/quotation.mjs';
import {OPTIONAL_STEPS,orderRoute} from '../domain/workflow.mjs';
import {products} from '../../scripts/products.mjs';import {el,button,panel,field,data,link,empty,badge,date,euro,actions,notice,owner} from '../ui/dom.mjs';import {ORDER_STATES,JOB_STATES} from '../domain/model.mjs';import {transitionOptions} from '../domain/commands.mjs';import {editTask,taskTable} from './tasks.mjs';import {materialDialog} from './materials.mjs';
export function editOrder(ctx,order={}){
  const lines=el('div',{class:'stack'});let index=0;
  function addLine(line={productId:'produto-1',configuration:{}}){
    const n=index++,row=el('section',{class:'order-line'}),config=el('div',{class:'form-grid'});
    const product=field('Produto',`product-${n}`,line.productId,{choices:products.map(p=>[p.id,`${p.name} · ${p.category}`])});
    const draw=values=>{const p=products.find(p=>p.id===product.querySelector('select').value);row.dataset.product=p.id;config.replaceChildren(...p.fields.map(f=>field(f.label,`${n}-${f.name}`,values?.[f.name]??f.value??f.options?.[0]??'',{type:f.type,choices:f.options,required:f.required,maxlength:f.maxLength,min:f.min,max:f.max,step:f.name==='quantity'?1:.1})));};
    row.dataset.index=n;product.querySelector('select').addEventListener('change',()=>draw({}));draw(line.configuration);
    row.append(el('div',{class:'line-head'},product,button('Remover linha',()=>row.remove(),'ghost')),config);lines.append(row);
  }
  (order.lines||[{productId:'produto-1',configuration:{}}]).forEach(addLine);
  const body=el('div',{class:'stack'},el('div',{class:'form-grid'},field('Cliente','clientId',order.clientId||ctx.state.clients[0]?.id,{choices:ctx.state.clients.map(c=>[c.id,c.name]),required:true}),field('Título','title',order.title,{required:true,maxlength:120}),field('Prazo','dueDate',order.dueDate,{type:'date'}),field('Head do trabalho','assigneeId',order.assigneeId||'',{choices:[['','Sem responsável'],...ctx.state.users.map(u=>[u.id,u.name])]}),field('Percurso comercial','pricingMode',order.pricingMode||'known',{choices:[['known','Preço conhecido — sem orçamento'],['quote','Requer orçamento']]}),field('Exige aprovação de arte','artRequired',order.artRequired===false?'no':'yes',{choices:[['yes','Sim'],['no','Não']]})),el('h3',{},'Produtos e personalização'),lines,button('+ Adicionar produto',()=>addLine(),'secondary'),field('Notas','notes',order.notes,{type:'textarea',maxlength:500}));
  ctx.openDialog({title:order.id?'Editar encomenda':order.pricingMode==='quote'?'Novo orçamento':'Nova encomenda',body,wide:true,onSave:form=>{const p=data(form);return ctx.dispatch('order.save',{...p,id:order.id,artRequired:p.artRequired==='yes',lines:[...lines.children].map(row=>({productId:row.dataset.product,configuration:Object.fromEntries(products.find(x=>x.id===row.dataset.product).fields.map(f=>[f.name,p[`${row.dataset.index}-${f.name}`]]))}))});}});
}
export function acceptOrder(ctx,o){
  const fixed=hasCatalogPrice(o);
  const selected=new Set(['production','ready',...(!fixed?['quote']:[]),...(o.artRequired?['approval']:[])]);
  const choices=el('div',{class:'route-choices'},...OPTIONAL_STEPS.filter(k=>k!=='quote'||!fixed).map(k=>el('label',{},el('input',{type:'checkbox',name:'steps',value:k,checked:selected.has(k)}),el('span',{},ORDER_STATES[k]))));
  const preview=el('p',{class:'notice','aria-live':'polite'});
  const draw=()=>{preview.textContent=['Aceite',...Array.from(choices.querySelectorAll('input:checked')).map(n=>ORDER_STATES[n.value]),'Entregue'].join(' → ');};
  choices.addEventListener('change',draw);draw();
  ctx.openDialog({title:'Aceitar e definir etapas',body:el('div',{class:'stack'},el('p',{},o.title),el('p',{class:'muted'},'Seleciona apenas as etapas necessárias. Aceite e Entregue fazem sempre parte do percurso. A passagem entre etapas é manual.'),fixed?notice('Produtos com preço definido no catálogo: esta encomenda não passa por orçamento.'):null,choices,preview),saveLabel:'Aceitar encomenda',onSave:form=>ctx.dispatch('order.accept',{id:o.id,steps:new FormData(form).getAll('steps')})});
}
export function render(ctx){const s=ctx.state,o=s.orders.find(o=>o.id===ctx.id);if(!o)return empty('Encomenda não encontrada.',link('Voltar ao pipeline','#pipeline','btn secondary'));const client=s.clients.find(c=>c.id===o.clientId),jobs=s.jobs.filter(j=>j.orderId===o.id),tasks=s.tasks.filter(t=>jobs.some(j=>j.id===t.jobId));
  const transitions=transitionOptions(o).filter(k=>o.status!=='quote'||k==='cancelled');const transition=field('Próxima etapa','next-status',transitions[0],{choices:transitions.map(k=>[k,ORDER_STATES[k]])});
  const change=()=>{const status=transition.querySelector('select').value;if(status==='cancelled')ctx.openDialog({title:'Cancelar encomenda?',body:notice('Os trabalhos abertos serão cancelados e as reservas libertadas. Consumos já realizados permanecem no histórico.'),saveLabel:'Cancelar encomenda',onSave:()=>ctx.dispatch('order.transition',{id:o.id,status})});else ctx.dispatch('order.transition',{id:o.id,status});};
  const top=el('div',{class:'order-banner'},el('div',{},link(client.name,`#cliente/${client.id}`,'eyebrow'),el('h2',{},o.title),el('p',{class:'muted'},`Prazo: ${date(o.dueDate)} · ${o.pricingMode==='known'?'Preço conhecido':'Sob orçamento'}`)),actions(badge(o.status),['new','accepted','quote','approval'].includes(o.status)?button('Editar encomenda',()=>editOrder(ctx,o),'secondary'):null));
  const control=panel('Acompanhar encomenda',el('div',{class:'panel-content stack'},el('p',{class:'small muted'},'Head do trabalho: '+owner(s,o.assigneeId)),o.status==='new'?button('Aceitar e definir etapas',()=>acceptOrder(ctx,o)):null,o.status==='new'?notice('Aguarda aceitação de um colaborador antes de avançar.'):el('div',{class:'order-route','aria-label':'Percurso desta encomenda'},...orderRoute(o).map(k=>el('span',{class:k===o.status?'current':'','aria-current':k===o.status?'step':undefined},ORDER_STATES[k]))),o.status==='quote'?actions(button(o.quotation?.status==='pending'?'Rever orçamento':'Orçamentar projeto',()=>quotationDialog(ctx,o),'secondary'),o.quotation?.status==='pending'?button('Aprovar orçamento',()=>ctx.dispatch('quote.approve',{id:o.id})):null):null,o.quotation?quotationSummary(o.quotation):null,transitions.length?actions(transition,button(o.status==='new'?'Cancelar encomenda':'Aplicar etapa',change)):notice('Encomenda encerrada.'),notice(o.artRequired?(o.artApproved?'Arte aprovada.':'A produção aguarda aprovação da arte.'):'Este trabalho não exige aprovação de arte.'),o.artRequired&&!o.artApproved&&o.status==='approval'?button('Registar aprovação da arte',()=>ctx.dispatch('order.approveArt',{id:o.id}),'secondary'):null,el('p',{class:'small muted'},o.notes||'Sem notas.')));
  const lineDetails=panel('Produtos personalizados',...o.lines.map(l=>{const p=products.find(p=>p.id===l.productId);return el('div',{class:'line-detail'},el('h3',{},p.name+' · '+p.category),el('dl',{class:'details'},p.fields.filter(f=>l.configuration[f.name]).flatMap(f=>[el('dt',{},f.label),el('dd',{},l.configuration[f.name])])));}));
  const work=panel('Produção e materiais',...jobs.map(j=>{const consumed=s.movements.filter(m=>m.jobId===j.id).reduce((n,m)=>n+m.costMilliEuro,0);return el('div',{class:'job-row'},el('div',{},el('strong',{},j.title),el('p',{class:'small muted'},`${JOB_STATES[j.status]} · Custo de filamento: ${euro(consumed)}`)),actions(j.status==='pending'&&o.status==='production'?button('Iniciar e reservar',()=>materialDialog(ctx,j),'secondary'):null,j.status==='active'?button('Confirmar consumo',()=>materialDialog(ctx,j,true)):null,j.status==='failed'&&!['cancelled','delivered'].includes(o.status)?button('Criar reimpressão',()=>ctx.dispatch('job.reprint',{jobId:j.id}),'secondary'):null,['pending','active'].includes(j.status)&&!['cancelled','delivered'].includes(o.status)?button('Cancelar trabalho',()=>ctx.openDialog({title:'Cancelar trabalho?',body:notice('A reserva será libertada. Se já houve consumo, confirma-o como falha antes de cancelar.'),onSave:()=>ctx.dispatch('job.cancel',{jobId:j.id}),saveLabel:'Cancelar trabalho'}),'ghost'):null));}));
  const history=s.history.filter(h=>h.entityId===o.id||jobs.some(j=>j.id===h.entityId)||tasks.some(t=>t.id===h.entityId)).slice().reverse();
  return el('div',{class:'stack'},link('← Pipeline','#pipeline','text-link'),top,el('div',{class:'order-grid'},lineDetails,control),(!o.route||o.route.includes('production'))?work:null,panel('Tarefas abertas do projeto',!['delivered','cancelled'].includes(o.status)?el('div',{class:'panel-action'},button('+ Nova tarefa',()=>editTask(ctx,{jobId:jobs[0]?.id}),'secondary')):null,taskTable(ctx,tasks.filter(t=>t.status!=='done'),{readOnly:['delivered','cancelled'].includes(o.status)})),panel('Histórico de tarefas concluídas',taskTable(ctx,tasks.filter(t=>t.status==='done'),{readOnly:['delivered','cancelled'].includes(o.status)})),panel('Histórico',history.length?history.map(h=>el('div',{class:'history-row'},el('span',{},h.description),el('span',{class:'muted small'},new Date(h.at).toLocaleString('pt-PT')+' · Administrador demo'))):empty('Sem alterações registadas.')));
}
